remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Bikers Map of Rotterdam Outdoors
description: "Assembled with love, by Sara Baldwin"
show_downloads: true
url: "https://rotterdamoutdoorbikermap.org"  
baseurl: "" 